trigger:
  branches:
    include:
      - main

jobs:
  - job: Train_Model
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.x'
      - script: |
          python -m pip install --upgrade pip
          pip install numpy scikit-learn
        displayName: 'Install Python packages'
      - script: |
          echo "Training the model"
          python train_model.py
        displayName: 'Train the model'

  - job: Deploy_Model
    dependsOn: Train_Model
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: |
          echo "Deploying the model"
          python deploy_model.py
        displayName: 'Deploy the model'
